/*
Executer ce script autant que db-abc-rdv-prd-useradm ou db-abc-rdv-prd-userapf.
Ce script permet d'insérer des données d'exemple dans les tables d'une base de données MariaDB pour le projet ABC-RDV. 
Le script est conçu pour être exécuté dans un environnement de production, db-abc-rdv-prd.
Il insère des données dans les tables Villes, Clients, Professionnels, Services et Reservations.
Il est important de noter que ce script suppose que les tables existent déjà et qu'elles sont vides avant l'insertion des données.
Il faut executer le script avec l'utilisateur ayant les droits d'insertion sur les tables.
*/

/*
Ce script ne contient pas COMMIT final !
*/

-- Insertion de 10 enregistrements dans la table 'Villes'
INSERT INTO db-abc-rdv-prd.Villes (nom_ville) VALUES
('Paris'),
('Lyon'),
('Marseille'),
('Nice'),
('Bordeaux'),
('Lille'),
('Strasbourg'),
('Toulouse'),
('Nantes'),
('Rennes');

-- Insertion de 50 enregistrements dans la table 'Clients'
INSERT INTO db-abc-rdv-prd.Clients (nom, email, historique_reservations) VALUES
('Jean Dupont', 'jean.dupont@email.com', '{"reservations": []}'),
('Marie Dubois', 'marie.dubois@email.com', '{"reservations": []}'),
('Pierre Martin', 'pierre.martin@email.com', '{"reservations": []}'),
('Sophie Leroy', 'sophie.leroy@email.com', '{"reservations": []}'),
('Lucie Bernard', 'lucie.bernard@email.com', '{"reservations": []}'),
('Thomas Petit', 'thomas.petit@email.com', '{"reservations": []}'),
('Amandine Moreau', 'amandine.moreau@email.com', '{"reservations": []}'),
('Nicolas Garcia', 'nicolas.garcia@email.com', '{"reservations": []}'),
('Emma Robert', 'emma.robert@email.com', '{"reservations": []}'),
('Mathieu Durand', 'mathieu.durand@email.com', '{"reservations": []}'),
('Chloé Lefevre', 'chloe.lefevre@email.com', '{"reservations": []}'),
('Antoine Simon', 'antoine.simon@email.com', '{"reservations": []}'),
('Camille Michel', 'camille.michel@email.com', '{"reservations": []}'),
('Alexandre Leclerc', 'alexandre.leclerc@email.com', '{"reservations": []}'),
('Alice Fournier', 'alice.fournier@email.com', '{"reservations": []}'),
('Guillaume Lemoine', 'guillaume.lemoine@email.com', '{"reservations": []}'),
('Julia Roux', 'julia.roux@email.com', '{"reservations": []}'),
('Julien Boyer', 'julien.boyer@email.com', '{"reservations": []}'),
('Laura Dubois', 'laura.dubois@email.com', '{"reservations": []}'),
('Maxime Lambert', 'maxime.lambert@email.com', '{"reservations": []}'),
('Océane Richard', 'oceane.richard@email.com', '{"reservations": []}'),
('Paul Durand', 'paul.durand@email.com', '{"reservations": []}'),
('Quentin Petit', 'quentin.petit@email.com', '{"reservations": []}'),
('Romain Lebrun', 'romain.lebrun@email.com', '{"reservations": []}'),
('Sarah Vincent', 'sarah.vincent@email.com', '{"reservations": []}'),
('Simon Roux', 'simon.roux@email.com', '{"reservations": []}'),
('Tom Michel', 'tom.michel@email.com', '{"reservations": []}'),
('Victor Lemoine', 'victor.lemoine@email.com', '{"reservations": []}'),
('Yannick Fournier', 'yannick.fournier@email.com', '{"reservations": []}'),
('Zoe Mercier', 'zoe.mercier@email.com', '{"reservations": []}'),
('Arthur Petit', 'arthur.petit@email.com', '{"reservations": []}'),
('Caroline Dubois', 'caroline.dubois@email.com', '{"reservations": []}'),
('Damien Lambert', 'damien.lambert@email.com', '{"reservations": []}'),
('Émilie Rousseau', 'emilie.rousseau@email.com', '{"reservations": []}'),
('Gabriel Simon', 'gabriel.simon@email.com', '{"reservations": []}'),
('Inès Garnier', 'ines.garnier@email.com', '{"reservations": []}'),
('Jérémy Lebrun', 'jeremy.lebrun@email.com', '{"reservations": []}'),
('Justine Leroy', 'justine.leroy@email.com', '{"reservations": []}'),
('Léa Martin', 'lea.martin@email.com', '{"reservations": []}'),
('Louis Robert', 'louis.robert@email.com', '{"reservations": []}'),
('Manon Garcia', 'manon.garcia@email.com', '{"reservations": []}'),
('Noémie Bernard', 'noemie.bernard@email.com', '{"reservations": []}'),
('Oscar Michel', 'oscar.michel@email.com', '{"reservations": []}'),
('Philippine Richard', 'philippine.richard@email.com', '{"reservations": []}'),
('Raphaël Morel', 'raphael.morel@email.com', '{"reservations": []}'),
('Solène Dubois', 'solene.dubois@email.com', '{"reservations": []}'),
('Tanguy Roux', 'tanguy.roux@email.com', '{"reservations": []}'),
('Ursula Leclerc', 'ursula.leclerc@email.com', '{"reservations": []}'),
('Vincent Boyer', 'vincent.boyer@email.com', '{"reservations": []}'),
('Yanis Leblanc', 'yanis.leblanc@email.com', '{"reservations": []}');

-- Insertion de 50 enregistrements dans la table 'Professionnels'
INSERT INTO db-abc-rdv-prd.Professionnels (nom, adresse, services, prix, agenda, notes, ville_id) VALUES
('Le Salon Chic', '12 rue de la Paix', '{"coupe": true, "coloration": true}', 75.00, '{"lundi": "9h-18h"}', 'Spécialiste en coupes modernes', (SELECT ville_id FROM Villes WHERE nom_ville = 'Paris')),
('Tendance Coiffure', '5 rue des Lilas', '{"brushing": true, "meches": true}', 50.00, '{"mardi": "10h-19h"}', 'Meilleur salon pour les brushings', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lyon')),
('L\'Atelier de Camille', '45 avenue des Champs', '{"balayage": true, "soins": true}', 120.00, '{"mercredi": "8h-17h"}', 'Maître coloriste', (SELECT ville_id FROM Villes WHERE nom_ville = 'Marseille')),
('Artisan Coiffeur', '92 rue du Faubourg', '{"coupe": true, "barbe": true}', 45.00, '{"jeudi": "11h-20h"}', 'Expert en coiffure masculine', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nice')),
('Style Urbain', '23 rue de la République', '{"coupe": true, "coloration": true, "barbe": true}', 60.00, '{"vendredi": "9h-18h"}', 'Ambiance jeune et dynamique', (SELECT ville_id FROM Villes WHERE nom_ville = 'Bordeaux')),
('Salon Beauté', '34 rue Victor Hugo', '{"brushing": true, "meches": true, "soins": true}', 80.00, '{"lundi": "10h-19h"}', 'Soins pour tous types de cheveux', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lille')),
('Coupes et Couleurs', '18 rue Nationale', '{"coloration": true, "lissage": true}', 150.00, '{"mardi": "9h-18h"}', 'Produits bio et naturels', (SELECT ville_id FROM Villes WHERE nom_ville = 'Strasbourg')),
('Barber Shop', '7 avenue Foch', '{"coupe": true, "barbe": true}', 40.00, '{"mercredi": "10h-19h"}', 'Taille de barbe traditionnelle', (SELECT ville_id FROM Villes WHERE nom_ville = 'Toulouse')),
('Le Coiffeur', '67 rue de la Gare', '{"coupe": true, "brushing": true}', 55.00, '{"jeudi": "9h-18h"}', 'Coiffure classique et élégante', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nantes')),
('Cheveux d\'Or', '81 rue de l\'Étoile', '{"balayage": true, "meches": true}', 130.00, '{"vendredi": "10h-19h"}', 'Spécialiste du blond polaire', (SELECT ville_id FROM Villes WHERE nom_ville = 'Rennes')),
('Glamour Coiffure', '15 rue Gambetta', '{"coiffure_soiree": true, "mariage": true}', 200.00, '{"samedi": "9h-18h"}', 'Coiffure de mariée sur-mesure', (SELECT ville_id FROM Villes WHERE nom_ville = 'Paris')),
('Beauté Moderne', '10 rue Voltaire', '{"coupe": true, "coloration": true, "soins": true}', 90.00, '{"dimanche": "10h-17h"}', 'Techniques de coloration avancées', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lyon')),
('Espace Coiffure', '22 place des Martyrs', '{"brushing": true, "coupe": true}', 65.00, '{"lundi": "8h-18h"}', 'Rapide et efficace', (SELECT ville_id FROM Villes WHERE nom_ville = 'Marseille')),
('Le Salon', '40 boulevard Carnot', '{"meches": true, "balayage": true}', 110.00, '{"mardi": "9h-19h"}', 'Des mèches lumineuses', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nice')),
('Le Monde de la Coiffure', '55 rue de l\'Alma', '{"coupe": true, "brushing": true, "lissage": true}', 140.00, '{"mercredi": "10h-18h"}', 'Lissage brésilien longue durée', (SELECT ville_id FROM Villes WHERE nom_ville = 'Bordeaux')),
('L\'Expert Cheveux', '31 rue Saint-Jean', '{"soins": true, "extension": true}', 180.00, '{"jeudi": "9h-17h"}', 'Soins profonds et extensions de qualité', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lille')),
('Hair Style', '4 rue Colbert', '{"coupe": true, "barbe": true}', 50.00, '{"vendredi": "10h-19h"}', 'Pour un style impeccable', (SELECT ville_id FROM Villes WHERE nom_ville = 'Strasbourg')),
('Barbier Moderne', '8 rue Thiers', '{"barbe": true}', 30.00, '{"lundi": "9h-18h"}', 'Taille de barbe avec serviette chaude', (SELECT ville_id FROM Villes WHERE nom_ville = 'Toulouse')),
('Coiffure Passion', '14 rue du Commerce', '{"coupe": true, "coloration": true}', 70.00, '{"mardi": "10h-19h"}', 'L\'art de la coiffure', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nantes')),
('Le Salon des Tendances', '28 rue de la Fontaine', '{"meches": true, "balayage": true, "soins": true}', 100.00, '{"mercredi": "9h-18h"}', 'À la pointe des tendances', (SELECT ville_id FROM Villes WHERE nom_ville = 'Rennes')),
('Votre Coiffeur', '3 rue de la Paix', '{"coupe": true, "coloration": true, "soins": true}', 85.00, '{"jeudi": "11h-20h"}', 'Une équipe à votre écoute', (SELECT ville_id FROM Villes WHERE nom_ville = 'Paris')),
('Les Ciseaux d\'Or', '17 rue des Lilas', '{"brushing": true, "meches": true}', 60.00, '{"vendredi": "9h-18h"}', 'Brushing parfait garanti', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lyon')),
('L\'Atelier de Sophie', '41 avenue des Champs', '{"balayage": true, "soins": true}', 130.00, '{"samedi": "10h-19h"}', 'Spécialiste des cheveux longs', (SELECT ville_id FROM Villes WHERE nom_ville = 'Marseille')),
('Salon Le Magnifique', '98 rue du Faubourg', '{"coupe": true, "barbe": true}', 55.00, '{"dimanche": "10h-17h"}', 'Pour un look soigné', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nice')),
('Coiffure Classique', '27 rue de la République', '{"coupe": true, "coloration": true, "barbe": true}', 70.00, '{"lundi": "8h-18h"}', 'Coupe classique et intemporelle', (SELECT ville_id FROM Villes WHERE nom_ville = 'Bordeaux')),
('Salon des Rêves', '39 rue Victor Hugo', '{"brushing": true, "meches": true, "soins": true}', 95.00, '{"mardi": "9h-19h"}', 'Pour des cheveux de rêve', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lille')),
('Maître Coiffeur', '12 rue Nationale', '{"coloration": true, "lissage": true}', 160.00, '{"mercredi": "10h-18h"}', 'Formé aux dernières techniques', (SELECT ville_id FROM Villes WHERE nom_ville = 'Strasbourg')),
('Barbier de France', '7 avenue Foch', '{"coupe": true, "barbe": true}', 50.00, '{"jeudi": "9h-17h"}', 'Service sur rendez-vous', (SELECT ville_id FROM Villes WHERE nom_ville = 'Toulouse')),
('Coiffure Élégance', '68 rue de la Gare', '{"coupe": true, "brushing": true}', 65.00, '{"vendredi": "10h-19h"}', 'Coiffure pour toutes les occasions', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nantes')),
('Couleur Lumière', '83 rue de l\'Étoile', '{"balayage": true, "meches": true}', 140.00, '{"lundi": "9h-18h"}', 'Mèches et balayages personnalisés', (SELECT ville_id FROM Villes WHERE nom_ville = 'Rennes')),
('L\'instant Coiffure', '15 rue Gambetta', '{"coiffure_soiree": true, "mariage": true}', 210.00, '{"mardi": "10h-19h"}', 'Coiffure de mariée et de cérémonie', (SELECT ville_id FROM Villes WHERE nom_ville = 'Paris')),
('Beauté d\'Aujourd\'hui', '10 rue Voltaire', '{"coupe": true, "coloration": true, "soins": true}', 100.00, '{"mercredi": "8h-17h"}', 'Un style qui vous ressemble', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lyon')),
('Espace Beauté', '22 place des Martyrs', '{"brushing": true, "coupe": true}', 75.00, '{"jeudi": "11h-20h"}', 'Un moment de détente', (SELECT ville_id FROM Villes WHERE nom_ville = 'Marseille')),
('Le Salon Prestige', '40 boulevard Carnot', '{"meches": true, "balayage": true}', 120.00, '{"vendredi": "9h-18h"}', 'Des cheveux sublimes', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nice')),
('Le Coiffeur du Coin', '55 rue de l\'Alma', '{"coupe": true, "brushing": true, "lissage": true}', 150.00, '{"samedi": "10h-19h"}', 'Pour toute la famille', (SELECT ville_id FROM Villes WHERE nom_ville = 'Bordeaux')),
('L\'art de la Coiffure', '31 rue Saint-Jean', '{"soins": true, "extension": true}', 190.00, '{"dimanche": "10h-17h"}', 'Des extensions de rêve', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lille')),
('Le Barbier', '4 rue Colbert', '{"coupe": true, "barbe": true}', 60.00, '{"lundi": "8h-18h"}', 'Le meilleur barbier de la ville', (SELECT ville_id FROM Villes WHERE nom_ville = 'Strasbourg')),
('Coiffure du Monde', '8 rue Thiers', '{"barbe": true}', 35.00, '{"mardi": "9h-19h"}', 'Une barbe parfaite en 30 minutes', (SELECT ville_id FROM Villes WHERE nom_ville = 'Toulouse')),
('Le Salon Éco', '14 rue du Commerce', '{"coupe": true, "coloration": true}', 80.00, '{"mercredi": "10h-18h"}', 'Produits écologiques', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nantes')),
('Le Salon Pro', '28 rue de la Fontaine', '{"meches": true, "balayage": true, "soins": true}', 110.00, '{"jeudi": "9h-17h"}', 'Une équipe de professionnels', (SELECT ville_id FROM Villes WHERE nom_ville = 'Rennes')),
('Coiffure à Domicile', '20 rue des Arts', '{"coupe": true, "brushing": true}', 70.00, '{"vendredi": "10h-19h"}', 'Service à domicile', (SELECT ville_id FROM Villes WHERE nom_ville = 'Paris')),
('Les Maîtres Coiffeurs', '19 rue de la Poste', '{"coupe": true, "coloration": true}', 95.00, '{"samedi": "9h-18h"}', 'Un service impeccable', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lyon')),
('La Coiffure Idéale', '33 avenue Jean Jaurès', '{"brushing": true, "lissage": true}', 145.00, '{"dimanche": "10h-17h"}', 'Le lissage parfait', (SELECT ville_id FROM Villes WHERE nom_ville = 'Marseille')),
('Salon des Anges', '65 rue du Jardin', '{"balayage": true, "meches": true}', 155.00, '{"lundi": "8h-18h"}', 'Pour un look d\'ange', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nice')),
('Le Salon du Port', '1 rue du Port', '{"coupe": true, "barbe": true}', 65.00, '{"mardi": "9h-19h"}', 'Face à la mer', (SELECT ville_id FROM Villes WHERE nom_ville = 'Bordeaux')),
('Barber House', '5 rue de la Liberté', '{"barbe": true}', 40.00, '{"mercredi": "10h-18h"}', 'Le temple de la barbe', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lille')),
('Le Salon Vintage', '11 rue Saint-Michel', '{"coupe": true, "brushing": true}', 85.00, '{"jeudi": "9h-17h"}', 'Un style rétro', (SELECT ville_id FROM Villes WHERE nom_ville = 'Strasbourg')),
('L\'Art de la Beauté', '27 rue des Lilas', '{"coloration": true, "soins": true}', 120.00, '{"vendredi": "10h-19h"}', 'Des soins en profondeur', (SELECT ville_id FROM Villes WHERE nom_ville = 'Toulouse')),
('Le Salon de Marie', '77 rue de la Paix', '{"meches": true, "balayage": true}', 135.00, '{"lundi": "9h-18h"}', 'Mèches et balayages', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nantes')),
('Coiffure Excellence', '99 rue de la Gare', '{"coupe": true, "coloration": true, "soins": true}', 115.00, '{"mardi": "10h-19h"}', 'Un service d\'excellence', (SELECT ville_id FROM Villes WHERE nom_ville = 'Rennes'));

-- Remplir les professionnels restants
INSERT INTO db-abc-rdv-prd.Professionnels (nom, adresse, services, prix, agenda, notes, ville_id) VALUES
('Le Salon Coquette', '10 rue de la Rose', '{"coupe": true, "coloration": true}', 80.00, '{"lundi": "9h-18h"}', 'Spécialiste en coupes pour femmes', (SELECT ville_id FROM Villes WHERE nom_ville = 'Paris')),
('Salon d\'Art', '22 place des Arts', '{"brushing": true, "meches": true}', 60.00, '{"mardi": "10h-19h"}', 'Meilleur salon pour les brushings', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lyon')),
('L\'Atelier du Style', '30 avenue du Soleil', '{"balayage": true, "soins": true}', 130.00, '{"mercredi": "8h-17h"}', 'Maître coloriste', (SELECT ville_id FROM Villes WHERE nom_ville = 'Marseille')),
('Coiffeur Expert', '56 rue du Port', '{"coupe": true, "barbe": true}', 50.00, '{"jeudi": "11h-20h"}', 'Expert en coiffure masculine', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nice')),
('Coiffure Tendance', '15 rue de la Gare', '{"coupe": true, "coloration": true, "barbe": true}', 70.00, '{"vendredi": "9h-18h"}', 'Ambiance jeune et dynamique', (SELECT ville_id FROM Villes WHERE nom_ville = 'Bordeaux')),
('Salon de la Beauté', '8 rue de la Mairie', '{"brushing": true, "meches": true, "soins": true}', 90.00, '{"lundi": "10h-19h"}', 'Soins pour tous types de cheveux', (SELECT ville_id FROM Villes WHERE nom_ville = 'Lille')),
('Le Ciseau d\'Or', '12 avenue de la Liberté', '{"coloration": true, "lissage": true}', 160.00, '{"mardi": "9h-18h"}', 'Produits bio et naturels', (SELECT ville_id FROM Villes WHERE nom_ville = 'Strasbourg')),
('Barbier de Luxe', '25 rue de la Plage', '{"coupe": true, "barbe": true}', 45.00, '{"mercredi": "10h-19h"}', 'Taille de barbe traditionnelle', (SELECT ville_id FROM Villes WHERE nom_ville = 'Toulouse')),
('Le Coiffeur de la Cité', '40 rue du Marché', '{"coupe": true, "brushing": true}', 60.00, '{"jeudi": "9h-18h"}', 'Coiffure classique et élégante', (SELECT ville_id FROM Villes WHERE nom_ville = 'Nantes')),
('Cheveux de Rêve', '70 rue du Canal', '{"balayage": true, "meches": true}', 140.00, '{"vendredi": "10h-19h"}', 'Spécialiste du blond polaire', (SELECT ville_id FROM Villes WHERE nom_ville = 'Rennes'));

-- Insertion de 50 enregistrements dans la table 'Services'
INSERT INTO db-abc-rdv-prd.Services (nom_service, description, prix, duree) VALUES
('Coupe Femme', 'Coupe et shampoing pour cheveux longs ou mi-longs.', 40.00, 60),
('Coupe Homme', 'Coupe pour cheveux courts.', 25.00, 30),
('Coupe & Brushing', 'Coupe, shampoing et brushing.', 50.00, 75),
('Brushing', 'Mise en forme des cheveux avec brosse et sèche-cheveux.', 25.00, 45),
('Coloration', 'Application d\'une couleur sur l\'ensemble de la chevelure.', 60.00, 90),
('Mèches', 'Création de mèches plus claires pour un effet de lumière.', 80.00, 120),
('Balayage', 'Technique d\'éclaircissement plus subtile que les mèches.', 95.00, 150),
('Barbe', 'Taille et entretien de la barbe.', 20.00, 30),
('Soins Capillaires', 'Traitement pour hydrater et nourrir les cheveux en profondeur.', 30.00, 45),
('Coiffure de Soirée', 'Coiffure élaborée pour une occasion spéciale.', 70.00, 90),
('Lissage Brésilien', 'Lissage durable et soignant.', 150.00, 180),
('Extension de cheveux', 'Pose d\'extensions pour gagner en volume et en longueur.', 200.00, 240),
('Coupe Enfant', 'Coupe pour les enfants de moins de 12 ans.', 15.00, 25),
('Décoloration', 'Éclaircissement de la couleur des cheveux.', 100.00, 120),
('Permanente', 'Boucles ou ondulations permanentes.', 110.00, 150),
('Taille de barbe', 'Taille précise de la barbe.', 25.00, 30),
('Coloration racine', 'Retouche de la couleur à la racine.', 45.00, 60),
('Mèches partielles', 'Mèches sur une section limitée des cheveux.', 60.00, 90),
('Balayage partiel', 'Balayage sur une section limitée des cheveux.', 75.00, 120),
('Chignon', 'Coiffure de soirée en chignon.', 65.00, 90),
('Coupe Homme + Barbe', 'Coupe pour homme et taille de la barbe.', 40.00, 60),
('Shampoing + Masque', 'Lavage et soin hydratant.', 20.00, 30),
('Soin à la kératine', 'Traitement pour cheveux abîmés.', 50.00, 60),
('Tresse', 'Coiffure avec tresses.', 35.00, 45),
('Coiffure de mariée', 'Coiffure spéciale pour un mariage.', 250.00, 180),
('Coloration homme', 'Coloration pour homme.', 40.00, 60),
('Mèches homme', 'Mèches pour homme.', 50.00, 75),
('Défrisage', 'Lissage permanent des cheveux.', 120.00, 150),
('Lissage japonais', 'Lissage permanent et très raide.', 250.00, 240),
('Taille de la moustache', 'Entretien de la moustache.', 10.00, 15),
('Teinture de cils', 'Teinture des cils.', 15.00, 20),
('Épilation du visage', 'Épilation du visage.', 20.00, 30),
('Soin des mains', 'Manucure simple.', 25.00, 30),
('Soin des pieds', 'Pédicure simple.', 30.00, 45),
('Massage du cuir chevelu', 'Massage relaxant.', 15.00, 20),
('Soin anti-chute', 'Soin pour la prévention de la chute des cheveux.', 40.00, 60),
('Mèches sur cheveux courts', 'Mèches sur cheveux courts.', 70.00, 90),
('Coiffure afro', 'Coiffure spécifique pour cheveux afro.', 85.00, 120),
('Tresses africaines', 'Réalisation de tresses africaines.', 150.00, 180),
('Coupe de frange', 'Coupe de la frange.', 10.00, 15),
('Soin express', 'Soin rapide pour cheveux.', 15.00, 20),
('Coloration ton sur ton', 'Coloration qui ne modifie pas la couleur naturelle.', 55.00, 75),
('Mèches blondes', 'Mèches pour un effet blond.', 85.00, 120),
('Mèches rousses', 'Mèches pour un effet roux.', 85.00, 120),
('Mèches fantaisistes', 'Mèches de couleurs vives.', 90.00, 120),
('Balayage blond', 'Balayage pour un effet blond.', 100.00, 150),
('Balayage roux', 'Balayage pour un effet roux.', 100.00, 150),
('Balayage caramel', 'Balayage pour un effet caramel.', 105.00, 150),
('Soin du cuir chevelu', 'Soin pour un cuir chevelu sain.', 25.00, 30),
('Soin anti-pelliculaire', 'Soin pour éliminer les pellicules.', 30.00, 45);


-- Insertion de 50 enregistrements dans la table 'Services'
INSERT INTO db-abc-rdv-prd.Services (nom_service, description, prix, duree) VALUES
('Coupe Femme', 'Coupe et shampoing pour cheveux longs ou mi-longs.', 40.00, 60),
('Coupe Homme', 'Coupe pour cheveux courts.', 25.00, 30),
('Coupe & Brushing', 'Coupe, shampoing et brushing.', 50.00, 75),
('Brushing', 'Mise en forme des cheveux avec brosse et sèche-cheveux.', 25.00, 45),
('Coloration', 'Application d\'une couleur sur l\'ensemble de la chevelure.', 60.00, 90),
('Mèches', 'Création de mèches plus claires pour un effet de lumière.', 80.00, 120),
('Balayage', 'Technique d\'éclaircissement plus subtile que les mèches.', 95.00, 150),
('Barbe', 'Taille et entretien de la barbe.', 20.00, 30),
('Soins Capillaires', 'Traitement pour hydrater et nourrir les cheveux en profondeur.', 30.00, 45),
('Coiffure de Soirée', 'Coiffure élaborée pour une occasion spéciale.', 70.00, 90),
('Lissage Brésilien', 'Lissage durable et soignant.', 150.00, 180),
('Extension de cheveux', 'Pose d\'extensions pour gagner en volume et en longueur.', 200.00, 240),
('Coupe Enfant', 'Coupe pour les enfants de moins de 12 ans.', 15.00, 25),
('Décoloration', 'Éclaircissement de la couleur des cheveux.', 100.00, 120),
('Permanente', 'Boucles ou ondulations permanentes.', 110.00, 150),
('Taille de barbe', 'Taille précise de la barbe.', 25.00, 30),
('Coloration racine', 'Retouche de la couleur à la racine.', 45.00, 60),
('Mèches partielles', 'Mèches sur une section limitée des cheveux.', 60.00, 90),
('Balayage partiel', 'Balayage sur une section limitée des cheveux.', 75.00, 120),
('Chignon', 'Coiffure de soirée en chignon.', 65.00, 90),
('Coupe Homme + Barbe', 'Coupe pour homme et taille de la barbe.', 40.00, 60),
('Shampoing + Masque', 'Lavage et soin hydratant.', 20.00, 30),
('Soin à la kératine', 'Traitement pour cheveux abîmés.', 50.00, 60),
('Tresse', 'Coiffure avec tresses.', 35.00, 45),
('Coiffure de mariée', 'Coiffure spéciale pour un mariage.', 250.00, 180),
('Coloration homme', 'Coloration pour homme.', 40.00, 60),
('Mèches homme', 'Mèches pour homme.', 50.00, 75),
('Défrisage', 'Lissage permanent des cheveux.', 120.00, 150),
('Lissage japonais', 'Lissage permanent et très raide.', 250.00, 240),
('Taille de la moustache', 'Entretien de la moustache.', 10.00, 15),
('Teinture de cils', 'Teinture des cils.', 15.00, 20),
('Épilation du visage', 'Épilation du visage.', 20.00, 30),
('Soin des mains', 'Manucure simple.', 25.00, 30),
('Soin des pieds', 'Pédicure simple.', 30.00, 45),
('Massage du cuir chevelu', 'Massage relaxant.', 15.00, 20),
('Soin anti-chute', 'Soin pour la prévention de la chute des cheveux.', 40.00, 60),
('Mèches sur cheveux courts', 'Mèches sur cheveux courts.', 70.00, 90),
('Coiffure afro', 'Coiffure spécifique pour cheveux afro.', 85.00, 120),
('Tresses africaines', 'Réalisation de tresses africaines.', 150.00, 180),
('Coupe de frange', 'Coupe de la frange.', 10.00, 15),
('Soin express', 'Soin rapide pour cheveux.', 15.00, 20),
('Coloration ton sur ton', 'Coloration qui ne modifie pas la couleur naturelle.', 55.00, 75),
('Mèches blondes', 'Mèches pour un effet blond.', 85.00, 120),
('Mèches rousses', 'Mèches pour un effet roux.', 85.00, 120),
('Mèches fantaisistes', 'Mèches de couleurs vives.', 90.00, 120),
('Balayage blond', 'Balayage pour un effet blond.', 100.00, 150),
('Balayage roux', 'Balayage pour un effet roux.', 100.00, 150),
('Balayage caramel', 'Balayage pour un effet caramel.', 105.00, 150),
('Soin du cuir chevelu', 'Soin pour un cuir chevelu sain.', 25.00, 30),
('Soin anti-pelliculaire', 'Soin pour éliminer les pellicules.', 30.00, 45);


-- Insertion de 50 enregistrements dans la table 'Reservations'
INSERT INTO db-abc-rdv-prd.Reservations (date_reservation, heure_reservation, client_id, professionnel_id, service_id) VALUES
('2024-10-01', '10:00:00', 1, 1, 1),
('2024-10-01', '14:30:00', 2, 2, 4),
('2024-10-02', '11:00:00', 3, 3, 2),
('2024-10-02', '16:00:00', 4, 4, 6),
('2024-10-03', '09:30:00', 5, 5, 3),
('2024-10-03', '15:00:00', 6, 6, 8),
('2024-10-04', '10:30:00', 7, 7, 5),
('2024-10-04', '13:00:00', 8, 8, 6),
('2024-10-05', '11:00:00', 9, 9, 4),
('2024-10-05', '16:00:00', 10, 10, 2),
('2024-10-06', '09:00:00', 11, 11, 1),
('2024-10-06', '14:00:00', 12, 12, 8),
('2024-10-07', '10:00:00', 13, 13, 9),
('2024-10-07', '15:30:00', 14, 14, 7),
('2024-10-08', '11:00:00', 15, 15, 13),
('2024-10-08', '16:00:00', 16, 16, 14),
('2024-10-09', '09:30:00', 17, 17, 10),
('2024-10-09', '15:00:00', 18, 18, 11),
('2024-10-10', '10:30:00', 19, 19, 12),
('2024-10-10', '13:00:00', 20, 20, 15),
('2024-10-11', '11:00:00', 21, 21, 1),
('2024-10-11', '16:00:00', 22, 22, 4),
('2024-10-12', '09:00:00', 23, 23, 7),
('2024-10-12', '14:00:00', 24, 24, 1),
('2024-10-13', '10:00:00', 25, 25, 2),
('2024-10-13', '15:30:00', 26, 26, 3),
('2024-10-14', '11:00:00', 27, 27, 4),
('2024-10-14', '16:00:00', 28, 28, 1),
('2024-10-15', '09:30:00', 29, 29, 6),
('2024-10-15', '15:00:00', 30, 30, 8),
('2024-10-16', '10:30:00', 31, 31, 2),
('2024-10-16', '13:00:00', 32, 32, 11),
('2024-10-17', '11:00:00', 33, 33, 9),
('2024-10-17', '16:00:00', 34, 34, 7),
('2024-10-18', '09:00:00', 35, 35, 14),
('2024-10-18', '14:00:00', 36, 36, 10),
('2024-10-19', '10:00:00', 37, 37, 10),
('2024-10-19', '15:30:00', 38, 38, 13),
('2024-10-20', '11:00:00', 39, 39, 12),
('2024-10-20', '16:00:00', 40, 40, 15),
('2024-10-21', '09:30:00', 41, 41, 1),
('2024-10-21', '15:00:00', 42, 42, 2),
('2024-10-22', '10:30:00', 43, 43, 4),
('2024-10-22', '13:00:00', 44, 44, 5),
('2024-10-23', '11:00:00', 45, 45, 2),
('2024-10-23', '16:00:00', 46, 46, 3),
('2024-10-24', '09:00:00', 47, 47, 8),
('2024-10-24', '14:00:00', 48, 48, 11),
('2024-10-25', '10:00:00', 49, 49, 9),
('2024-10-25', '15:30:00', 50, 50, 7);


-- Insertion de 50 enregistrements dans la table 'Avis'
INSERT INTO db-abc-rdv-prd.Avis (note, commentaire, client_id, professionnel_id) VALUES
(5, 'Excellent service, très professionnel.', 1, 1),
(4, 'Bonne coupe, mais un peu d\'attente.', 2, 2),
(5, 'Rapide et efficace, je recommande.', 3, 3),
(5, 'Le balayage est parfait, exactement ce que je voulais.', 4, 4),
(4, 'Très bon accueil, la coupe est bien.', 5, 5),
(5, 'Taille de barbe parfaite.', 6, 6),
(5, 'J\'adore ma nouvelle couleur, merci !', 7, 7),
(3, 'Satisfaite, mais le prix est un peu élevé.', 8, 8),
(4, 'Brushing impeccable.', 9, 9),
(5, 'Superbe coupe, très à l\'aise.', 10, 10),
(5, 'Coupe et brushing au top.', 11, 11),
(4, 'Super barbier, très précis.', 12, 12),
(5, 'Soins exceptionnels, mes cheveux sont magnifiques.', 13, 13),
(5, 'Balayage très naturel, j\'y retournerai.', 14, 14),
(4, 'Coupe pour enfant réussie.', 15, 15),
(5, 'Décoloration sans aucun dommage.', 16, 16),
(5, 'Coiffure de soirée sublime.', 17, 17),
(4, 'Lissage brésilien efficace.', 18, 18),
(5, 'J\'adore mes extensions, très naturelles.', 19, 19),
(5, 'Permanente parfaite, les boucles tiennent.', 20, 20),
(5, 'Très bon accueil, service impeccable.', 21, 21),
(4, 'Super brushing, mais un peu long.', 22, 22),
(5, 'Balayage exceptionnel.', 23, 23),
(5, 'Service très pro, rien à dire.', 24, 24),
(4, 'Coupe homme classique et efficace.', 25, 25),
(5, 'Coupe et brushing impeccables.', 26, 26),
(5, 'Le brushing est parfait.', 27, 27),
(4, 'Coupe homme réussie, mais un peu d\'attente.', 28, 28),
(5, 'J\'adore mes mèches.', 29, 29),
(5, 'Taille de barbe au top.', 30, 30),
(4, 'Coupe classique et propre.', 31, 31),
(5, 'Lissage brésilien très réussi.', 32, 32),
(5, 'Soins profonds, mes cheveux revivent.', 33, 33),
(4, 'Balayage subtil et réussi.', 34, 34),
(5, 'Décoloration parfaite.', 35, 35),
(5, 'Coiffure de soirée magnifique.', 36, 36),
(4, 'Coiffure de soirée très créative.', 37, 37),
(5, 'Coupe pour enfant bien faite.', 38, 38),
(5, 'Extensions très bien posées.', 39, 39),
(4, 'Permanente bien faite, je suis contente.', 40, 40),
(5, 'Coupe femme parfaite.', 41, 41),
(5, 'Coupe homme très réussie.', 42, 42),
(4, 'Brushing impeccable.', 43, 43),
(5, 'Coloration très bien faite.', 44, 44),
(5, 'Coupe homme réussie.', 45, 45),
(4, 'Coupe et brushing efficaces.', 46, 46),
(5, 'Barbe bien taillée.', 47, 47),
(5, 'Lissage brésilien parfait.', 48, 48),
(4, 'Soins capillaires très agréables.', 49, 49),
(5, 'Balayage parfait, je reviendrai.', 50, 50);
